include tls.conf;
include common_headers.conf;

client_max_body_size 0;
proxy_read_timeout 3600;
proxy_send_timeout 3600;

location / {
  proxy_hide_header Strict-Transport-Security;   # use ours, not Nextcloud's weaker one
  proxy_pass http://127.0.0.1:11000$request_uri;

  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Port $server_port;
  proxy_set_header X-Forwarded-Scheme $scheme;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header Host $host;
  proxy_set_header Early-Data $ssl_early_data;

  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $connection_upgrade;
}

ssl_dhparam /etc/dhparam;
ssl_early_data on;
