Syslog			yes
SyslogSuccess		yes
Canonicalization	relaxed/relaxed
Mode			sv
OversignHeaders		From
Socket			inet:12301@127.0.0.1
UserID			opendkim
UMask			007
PidFile			/run/opendkim/opendkim.pid
TrustAnchorFile		/usr/share/dns/root.key
KeyTable /etc/opendkim/KeyTable
SigningTable refile:/etc/opendkim/SigningTable
InternalHosts		/etc/opendkim/TrustedHosts
SignHeaders From,Sender,Reply-To,Subject,Date,Message-ID,To,Cc,MIME-Version,Content-Type,Content-Transfer-Encoding,Content-ID,Content-Description,Resent-Date,Resent-From,Resent-Sender,Resent-To,Resent-Cc,Resent-Message-ID,In-Reply-To,References,List-Id,List-Help,List-Unsubscribe,List-Unsubscribe-Post,List-Subscribe,List-Post,List-Owner,List-Archive,Feedback-ID
