Syslog			yes
SyslogSuccess		yes
Canonicalization	relaxed/relaxed
Mode			sv
OversignHeaders		From
Socket			inet:12301@127.0.0.1
UserID			opendkim
UMask			007
PidFile			/run/opendkim/opendkim.pid
TrustAnchorFile		/usr/share/dns/root.key
KeyTable /etc/opendkim/KeyTable
SigningTable refile:/etc/opendkim/SigningTable
