Syslog			yes
SyslogSuccess		yes
Canonicalization	relaxed/relaxed
Mode			sv
OversignHeaders		From
Domain			alvarezmagan.com
Selector		mail
KeyFile			/etc/opendkim/keys/alvarezmagan.com/mail.private
Socket			inet:12301@127.0.0.1
UserID			opendkim
UMask			007
PidFile			/run/opendkim/opendkim.pid
TrustAnchorFile		/usr/share/dns/root.key
