# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/alvarezmagan.com
cert = /etc/letsencrypt/live/alvarezmagan.com/cert.pem
privkey = /etc/letsencrypt/live/alvarezmagan.com/privkey.pem
chain = /etc/letsencrypt/live/alvarezmagan.com/chain.pem
fullchain = /etc/letsencrypt/live/alvarezmagan.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 0acd7283502aeb0c4c422eb99a325679
authenticator = dns-cloudflare
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
dns_cloudflare_propagation_seconds = 25
dns_cloudflare_credentials = /root/.secrets/certbot/cloudflare.ini
