# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/alvarezrosa.com
cert = /etc/letsencrypt/live/alvarezrosa.com/cert.pem
privkey = /etc/letsencrypt/live/alvarezrosa.com/privkey.pem
chain = /etc/letsencrypt/live/alvarezrosa.com/chain.pem
fullchain = /etc/letsencrypt/live/alvarezrosa.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 0acd7283502aeb0c4c422eb99a325679
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
