tunnel: eb9fdd55-490a-4bc7-b67d-847cb658cdc6
credentials-file: /etc/cloudflared/eb9fdd55-490a-4bc7-b67d-847cb658cdc6.json

ingress:
  - hostname: tunnel.alvarezrosa.com
    service: ssh://localhost:22
  - service: http_status:404
