upstream analytics_backend {
  server 127.0.0.1:3000;
  keepalive 32;
}

server {
  include tls.conf;
  server_name analytics.alvarezrosa.com;

  ssl_certificate /etc/letsencrypt/live/alvarezrosa.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/alvarezrosa.com/privkey.pem;

  include common_headers.conf;

  location / {
    include proxy_params;
    proxy_pass http://analytics_backend;
  }
}
