server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;
    http2 on;
    server_name analytics.alvarezrosa.com;

    ssl_certificate /etc/letsencrypt/live/analytics.alvarezrosa.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/analytics.alvarezrosa.com/privkey.pem;

    add_header Alt-Svc 'h3=":443"; ma=604800';

    location / {
        include proxy_params;
        proxy_pass http://127.0.0.1:3000;
    }
}
