upstream unwall_api {
  server 127.0.0.1:3001;
  keepalive 32;
}

server {
  include tls.conf;
  server_name api.unwall.app;

  ssl_certificate /etc/letsencrypt/live/api.unwall.app/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/api.unwall.app/privkey.pem;

  include common_headers.conf;

  location / {
    include proxy_params;
    proxy_hide_header X-Frame-Options;
    proxy_hide_header Content-Security-Policy;
    proxy_pass http://unwall_api;
  }
}
