limit_req_zone $binary_remote_addr zone=subscribe:10m rate=6r/m;

upstream api_alvarezrosa {
  server 127.0.0.1:8000;
  keepalive 32;
}

server {
  include tls.conf;
  server_name api.alvarezrosa.com;

  ssl_certificate /etc/letsencrypt/live/alvarezrosa.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/alvarezrosa.com/privkey.pem;

  include common_headers.conf;

  location = /subscribe {
    limit_req zone=subscribe burst=4 nodelay;
    limit_req_status 429;
    include proxy_params;
    proxy_pass http://api_alvarezrosa;
  }

  location / {
    include proxy_params;
    proxy_pass http://api_alvarezrosa;
  }
}
