server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;
    http2 on;
    server_name api.unwall.app;

    ssl_certificate /etc/letsencrypt/live/api.unwall.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.unwall.app/privkey.pem;

    add_header Alt-Svc 'h3=":443"; ma=604800';

    location / {
        include proxy_params;
        proxy_hide_header X-Frame-Options;
        proxy_hide_header Content-Security-Policy;
        proxy_pass http://127.0.0.1:3001;
    }
}
