server {
  include tls.conf;
  server_name beta.alvarezrosa.com;

  ssl_certificate /etc/letsencrypt/live/alvarezrosa.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/alvarezrosa.com/privkey.pem;
  ssl_early_data on;

  include common_headers.conf;

  root /srv/beta.alvarezrosa.com;
  index index.html;
  error_page 404 /404/index.html;

  auth_basic "Beta site";
  auth_basic_user_file /etc/nginx/.htpasswd-beta;

  location / { try_files $uri $uri/ =404; }

  include static_assets.conf;
}
