server {
  include tls.conf;
  server_name chat.alvarezrosa.com;

  ssl_certificate /etc/letsencrypt/live/alvarezrosa.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/alvarezrosa.com/privkey.pem;

  include common_headers.conf;
  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header Content-Security-Policy "frame-ancestors 'self'" always;
  add_header Cache-Control "no-cache" always;

  root /usr/share/element-web;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  include static_assets.conf;
}
