server {
  server_name cloud.alvarezrosa.com;

  ssl_certificate /etc/letsencrypt/live/alvarezrosa.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/alvarezrosa.com/privkey.pem;

  include cloud_backend.conf;
}

server {
  server_name cloud.alvarezmagan.com;

  ssl_certificate /etc/letsencrypt/live/alvarezmagan.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/alvarezmagan.com/privkey.pem;

  include cloud_backend.conf;
}
