server {
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 443 quic;
    listen [::]:443 quic;
    http2 on;
    server_name david.alvarezmagan.com;

    ssl_certificate /etc/letsencrypt/live/david.alvarezmagan.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/david.alvarezmagan.com/privkey.pem;

    add_header Alt-Svc 'h3=":443"; ma=604800';

    root /srv/david.alvarezrosa.com;
    index index.html;
    error_page 404 /404/index.html;

    location / {
        try_files $uri $uri/ =404;
        add_header Cache-Control "public, max-age=600, s-maxage=31536000";
    }

    location ~* \.(woff2?|ttf|webp|png|jpe?g|ico|svg|css|js)$ {
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;
    }
}
