server {
  include tls.conf;
  server_name david.alvarezmagan.com;

  ssl_certificate /etc/letsencrypt/live/alvarezmagan.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/alvarezmagan.com/privkey.pem;
  ssl_early_data on;

  include common_headers.conf;

  root /srv/david.alvarezrosa.com;
  index index.html;
  error_page 404 /404/index.html;

  location / {
    try_files $uri $uri/ =404;
    include common_headers.conf;
    add_header Cache-Control "public, max-age=600, s-maxage=31536000";
  }

  include static_assets.conf;
}
