map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

server {
  listen 80;
  listen [::]:80;
  server_name _;

  location ^~ /.well-known/acme-challenge/ {
    root /var/www/acme;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl default_server;
  listen [::]:443 ssl default_server;
  listen 443 quic default_server;
  listen [::]:443 quic default_server;
  http2 on;

  ssl_certificate /etc/lego/certificates/213.32.19.229.crt;
  ssl_certificate_key /etc/lego/certificates/213.32.19.229.key;

  return 444;
}
