server {
  include tls.conf;
  server_name irc.alvarezrosa.com;

  ssl_certificate /etc/letsencrypt/live/alvarezrosa.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/alvarezrosa.com/privkey.pem;

  include common_headers.conf;

  location / {
    proxy_pass http://127.0.0.1:6677;
    include proxy_params;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }
}
