server {
  include tls.conf;
  server_name meet.alvarezmagan.com;

  ssl_certificate /etc/letsencrypt/live/alvarezmagan.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/alvarezmagan.com/privkey.pem;

  include common_headers.conf;

  return 301 https://cloud.alvarezmagan.com/apps/spreed$request_uri;
}
