server {
  include tls.conf;
  server_name recomprehension.com www.recomprehension.com;

  ssl_certificate /etc/letsencrypt/live/recomprehension.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/recomprehension.com/privkey.pem;
  ssl_early_data on;

  include common_headers.conf;

  root /srv/recomprehension.com/Website;
  index index.html;

  if ($host = www.recomprehension.com) {
    return 301 https://recomprehension.com$request_uri;
  }

  location ^~ /api/ { return 404; }
  location ~ \.php$ { return 404; }

  location / {
    try_files $uri $uri/ =404;
    include common_headers.conf;
    add_header Cache-Control "max-age=0, public";
  }

  include static_assets.conf;
}
