server {
  include tls.conf;
  server_name share.alvarezrosa.com;

  ssl_certificate /etc/letsencrypt/live/alvarezrosa.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/alvarezrosa.com/privkey.pem;

  include common_headers.conf;

  return 301 https://cloud.alvarezrosa.com/apps/files$request_uri;
}
