server {
  include tls.conf;
  server_name status.alvarezrosa.com;

  ssl_certificate /etc/letsencrypt/live/alvarezrosa.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/alvarezrosa.com/privkey.pem;
  ssl_early_data on;

  include common_headers.conf;

  location = / { return 302 /status/main; }

  location / {
    proxy_pass http://127.0.0.1:3011;
    include proxy_params;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }
}
