dovecot_config_version = 2.4.0
dovecot_storage_version = 2.4.0

protocols = imap

ssl = required
ssl_server_cert_file = /etc/letsencrypt/live/alvarezmagan.com/fullchain.pem
ssl_server_key_file = /etc/letsencrypt/live/alvarezmagan.com/privkey.pem
ssl_min_protocol = TLSv1.2

mail_driver = maildir
mail_path = /var/mail/vmail/%{user | domain}/%{user | username}
mail_privileged_group = mail

passdb passwd-file {
  passwd_file_path = /etc/dovecot/users
}

userdb static {
  fields {
    uid = vmail
    gid = vmail
    home = /var/mail/vmail/%{user | domain}/%{user | username}
  }
}

namespace inbox {
  inbox = yes
  mailbox Drafts {
    special_use = \Drafts
  }
  mailbox Junk {
    special_use = \Junk
  }
  mailbox Sent {
    special_use = \Sent
  }
  mailbox Trash {
    special_use = \Trash
  }
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}

service imap-login {
  inet_listener imap {
    port = 0
  }
}

local_name mail.alvarezrosa.com {
  ssl_server_cert_file = /etc/letsencrypt/live/alvarezrosa.com/fullchain.pem
  ssl_server_key_file = /etc/letsencrypt/live/alvarezrosa.com/privkey.pem
}
