sieve_plugins = sieve_imapsieve sieve_extprograms
sieve_global_extensions {
  vnd.dovecot.pipe = yes
}
sieve_pipe_bin_dir = /etc/dovecot/sieve-bin

sieve_script spam-to-junk {
  type = before
  path = /etc/dovecot/sieve/spam-to-junk.sieve
}

protocol lmtp {
  mail_plugins {
    sieve = yes
  }
}

protocol imap {
  mail_plugins {
    imap_sieve = yes
  }
}

service lmtp {
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    user = postfix
    group = postfix
    mode = 0600
  }
}

mailbox Junk {
  sieve_script report-spam-copy {
    type = before
    cause = copy
    path = /etc/dovecot/sieve/report-spam.sieve
  }
  sieve_script report-spam-append {
    type = before
    cause = append
    path = /etc/dovecot/sieve/report-spam.sieve
  }
}

imapsieve_from Junk {
  sieve_script report-ham {
    type = before
    cause = copy
    path = /etc/dovecot/sieve/report-ham.sieve
  }
}
